//PRODUCT
export const POST_STORE = 'POST_STORE';
export const POST_PRODUCT = 'POST_PRODUCT';
export const GET_PRODUCT = 'GET_PRODUCT';
//PRODUCT FILTERS
export const ORDER_PRODUCTS = 'ORDER_PRODUCTS';
export const FILTER_PRODUCTS = 'FILTER_PRODUCTS';
export const GET_PRODUCT_DETAIL = 'GET_PRODUCT_DETAIL';
export const GET_PRODUCT_TYPES = 'GET_PRODUCT_TYPES';
//PRODUCT ORDERS
export const GET_PRODUCT_DETAIL_ORDER_STOCK = 'GET_PRODUCT_DETAIL_ORDER_STOCK';
export const GET_PRODUCT_DETAIL_ORDER_PRICE = 'GET_PRODUCT_PRODUCT_ORDER_STOCK';
export const GET_PRODUCT_DETAIL_ORDER_AZ = 'GET_PRODUCT_DETAIL_ORDER_AZ';
export const GET_PRODUCT_DETAIL_ORDER_ZA = 'GET_PRODUCT_DETAIL_ORDER_ZA';

//AUTH
export const LOGIN = 'LOGIN';
export const LOGOUT = 'LOGOUT';
export const FIREBASE_ERR = 'FIREBASE_ERR';

//STORE
export const GET_STORES = 'GET_STORES';
export const SEARCH_BY_NAME = 'SEARCH_BY_NAME';
export const SEARCH_BY_ID = 'SEARCH_BY_ID';
export const ADD_ITEMS_TO_CART = 'ADD_ITEMS_TO_CART';
export const SET_CART = 'SET_CART';

export const ORDER_STORE = 'ORDER_STORE';
export const FILTER_STORE = 'FILTER_STORE';

//SHOPING CART
export const SHOPPING_CART_TYPES = {
    ADD_TO_CART: 'ADD_TO_CART',
    SET_TO_CART: 'SET_TO_CART',
    REMOVE_ONE_FROM_CART: 'REMOVE_ONE_FROM_CART',
    REMOVE_ALL_FROM_CART: 'REMOVE_ALL_FROM_CART',
    CLEAR_CART: 'CLEAR_CART',
};

//CLOUDINARY
// export const CLOUDINARY_IMAGES = {
//     GET_STORE_IMAGES: 'GET_STORES_IMAGES',
//     GET_PRODUCT_IMAGES: 'GET_PRODUCT_IMAGES',
// };
