//PRODUCT
export const POST_STORE = 'POST_STORE';
export const POST_PRODUCT = 'POST_PRODUCT';
export const GET_PRODUCT = 'GET_PRODUCT';
//PRODUCT FILTERS
export const FILTER_PRODUCTS = 'FILTER_PRODUCTS'
export const GET_PRODUCT_DETAIL = 'GET_PRODUCT_DETAIL';
export const GET_PRODUCT_DETAIL_NAME = 'GET_PRODUCT_DETAIL_NAME';
export const GET_PRODUCT_DETAIL_TYPE = 'GET_PRODUCT_DETAIL_TYPE';
export const GET_PRODUCT_DETAIL_STOCK = 'GET_PRODUCT_DETAIL_STOCK';
export const GET_PRODUCT_DETAIL_PRICE = 'GET_PRODUCT_DETAIL_PRICE';
//PRODUCT ORDERS
export const GET_PRODUCT_DETAIL_ORDER_STOCK = 'GET_PRODUCT_DETAIL_ORDER_STOCK'
export const GET_PRODUCT_DETAIL_ORDER_PRICE = 'GET_PRODUCT_PRODUCT_ORDER_STOCK'
export const GET_PRODUCT_DETAIL_ORDER_AZ = 'GET_PRODUCT_DETAIL_ORDER_AZ';
export const GET_PRODUCT_DETAIL_ORDER_ZA = 'GET_PRODUCT_DETAIL_ORDER_ZA';


//AUTH
export const LOGIN = 'LOGIN';
export const LOGOUT = 'LOGOUT';
export const FIREBASE_ERR = 'FIREBASE_ERR';

//STORE
export const GET_STORES = 'GET_STORES';
export const SEARCH_BY_NAME = 'SEARCH_BY_NAME';
export const SEARCH_BY_ID = 'SEARCH_BY_ID';

// SHOPPING CART
export const SHOPPING_CART_TYPES = {
    ADD_TO_CART: 'ADD_TO_CART',
    REMOVE_ONE_FROM_CART: 'REMOVE_ONE_FROM_CART',
    REMOVE_ALL_FROM_CART: 'REMOVE_ALL_FROM_CART',
    CLEAR_CART: 'CLEAR_CART',
};
