export const POST_STORE = 'POST_STORE';
export const POST_PRODUCT = 'POST_PRODUCT';
export const LOGIN = 'LOGIN';
export const LOGOUT = 'LOGOUT';
export const FIREBASE_ERR = 'FIREBASE_ERR';
export const GET_STORES = 'GET_STORES';
export const SEARCH_BY_NAME = 'SEARCH_BY_NAME';

// SHOPPING CART
export const SHOPPING_CART_TYPES = {
    ADD_TO_CART: 'ADD_TO_CART',
    REMOVE_ONE_FROM_CART: 'REMOVE_ONE_FROM_CART',
    REMOVE_ALL_FROM_CART: 'REMOVE_ALL_FROM_CART',
    CLEAR_CART: 'CLEAR_CART',
};
